INSERT INTO INGREDIENTE (ID, DESCRICAO, VALOR) values (1, 'Alface', 0.40);
INSERT INTO INGREDIENTE (ID, DESCRICAO, VALOR) values (2, 'Bacon', 2.00);
INSERT INTO INGREDIENTE (ID, DESCRICAO, VALOR) values (3, 'Hamburguer de carne', 3.00);
INSERT INTO INGREDIENTE (ID, DESCRICAO, VALOR) values (4, 'Ovo', 0.80);
INSERT INTO INGREDIENTE (ID, DESCRICAO, VALOR) values (5, 'Queijo', 1.50);